=== bcmissrain/PlanetWar/PlanetWar/Assets/Scripts/XmlDefine/Level.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  attributeFormDefault="unqualified"
>
  <xs:element name="level">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="levelDefine" type="levelDefine"/>
        <xs:element name="masterList" type="masterList" />
        <xs:element name="starList" type="starList"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="levelDefine">
    <xs:sequence>
      <xs:element name="levelId" type="xs:int"/>
      <xs:element name="levelOrder" type="xs:int"/>
      <xs:element name="levelDes" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="masterList">
    <xs:sequence>
      <xs:element name="master" type="master" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="starList">
    <xs:sequence>
      <xs:element name="star" type="star" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="master">
    <xs:sequence>
      <xs:element name="masterId" type="xs:int"/>
      <xs:element name="enemyId" type="xs:int"/>
      <xs:element name="theme">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Grey" />
            <xs:enumeration value="Blue" />
            <xs:enumeration value="Red" />
            <xs:enumeration value="Green" />
            <xs:enumeration value="Yellow" />
            <xs:enumeration value="Orange" />
            <xs:enumeration value="Black" />
            <xs:enumeration value="White" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="controllerType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Human" />
            <xs:enumeration value="Computer" />
            <xs:enumeration value="None" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="aiType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Teacher" />
            <xs:enumeration value="Random" />
            <xs:enumeration value="Peace" />
            <xs:enumeration value="Attack" />
            <xs:enumeration value="Coward" />
            <xs:enumeration value="God" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="thinkTime" type="xs:float"/>
      <xs:element name="masterName" type="xs:string"/>
      <xs:element name="masterDes" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="star">
    <xs:sequence>
      <xs:element name="starId" type="xs:int"/>
      <xs:element name="masterId" type="xs:int"/>
      <xs:element name="starParentId" type="xs:int"/>
      <xs:element name="rotateSpeed" type="xs:float"/>
      <xs:element name="position" type="vector3" />
      <xs:element name="starType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TroopStar" />
            <xs:enumeration value="DefenceStar" />
            <xs:enumeration value="MasterStar" />
            <xs:enumeration value="DoorStar" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="starLevel">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:enumeration value="0" />
            <xs:enumeration value="1" />
            <xs:enumeration value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="maxTroop" type="xs:int"/>
      <xs:element name="startTroopNum" type="xs:int"/>
      <xs:element name="bornTime" type="xs:float"/>
      <xs:element name="bornNum" type="xs:int"/>
      <xs:element name="detectScope" type="xs:float"/>
      <xs:element name="shipFlySpeed" type="xs:float"/>
      <xs:element name="shipShowType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Cloud" />
            <xs:enumeration value="Ring" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="thinkTime" type="xs:float"/>
      <xs:element name="ringLength" type="xs:float"/>
      <xs:element name="ringDepth" type="xs:float"/>
      <xs:element name="ringAddition" type="xs:float"/>
      <xs:element name="sendShipTime" type="xs:float"/>
      <xs:element name="sendShipNum" type="xs:float"/>
      <xs:element name="starDes" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name ="vector3">
    <xs:sequence>
      <xs:element name="x" type="xs:float" />
      <xs:element name="y" type="xs:float" />
      <xs:element name="z" type="xs:float" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== bcmissrain/PlanetWar/PlanetWar/Assets/Resources/LevelConfig/level0-0.xml
<?xml version="1.0" encoding="utf-8" ?>
<level xsi:noNamespaceSchemaLocation="../../Scripts/xmlDefine/Level.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <levelDefine>
    <levelId>0</levelId>
    <levelOrder>0</levelOrder>
    <levelDes>Level 0</levelDes>
  </levelDefine>
  <masterList>
    <master>
      <masterId>0</masterId>
      <enemyId>-1</enemyId>
      <theme>Grey</theme>
      <controllerType>None</controllerType>
      <aiType>Teacher</aiType>
      <thinkTime>10</thinkTime>
      <masterName>Teacher 0</masterName>
      <masterDes>Teacher 0</masterDes>
    </master>
    <master>
      <masterId>1</masterId>
      <enemyId>2</enemyId>
      <theme>Blue</theme>
      <controllerType>Human</controllerType>
      <aiType>God</aiType>
      <thinkTime>10</thinkTime>
      <masterName>Me</masterName>
      <masterDes>Me</masterDes>
    </master>
    <master>
      <masterId>2</masterId>
      <enemyId>1</enemyId>
      <theme>Red</theme>
      <controllerType>Computer</controllerType>
      <aiType>Coward</aiType>
      <thinkTime>5</thinkTime>
      <masterName>Enemy 0</masterName>
      <masterDes>Enemy 1</masterDes>
    </master>
  </masterList>
  <starList>
    <star>
      <starId>0</starId>
      <masterId>0</masterId>
      <starParentId>-1</starParentId>
      <rotateSpeed>0</rotateSpeed>
      <position>
        <x>0</x>
        <y>0</y>
        <z>10</z>
      </position>
      <starType>TroopStar</starType>
      <starLevel>0</starLevel>
      <maxTroop>30</maxTroop>
      <startTroopNum>15</startTroopNum>
      <bornTime>1</bornTime>
      <bornNum>1</bornNum>
      <detectScope>2</detectScope>
      <shipFlySpeed>2</shipFlySpeed>
      <shipShowType>Cloud</shipShowType>
      <thinkTime>3</thinkTime>
      <ringLength>1</ringLength>
      <ringDepth>0.3</ringDepth>
      <ringAddition>1.2</ringAddition>
      <sendShipTime>0.3</sendShipTime>
      <sendShipNum>5</sendShipNum>
      <starDes>Star None</starDes>
    </star>
    <star>
      <starId>1</starId>
      <masterId>1</masterId>
      <starParentId>-1</starParentId>
      <rotateSpeed>0</rotateSpeed>
      <position>
        <x>-8</x>
        <y>-2</y>
        <z>0</z>
      </position>
      <starType>TroopStar</starType>
      <starLevel>1</starLevel>
      <maxTroop>30</maxTroop>
      <startTroopNum>30</startTroopNum>
      <bornTime>1</bornTime>
      <bornNum>1</bornNum>
      <detectScope>2</detectScope>
      <shipFlySpeed>2</shipFlySpeed>
      <shipShowType>Cloud</shipShowType>
      <thinkTime>3</thinkTime>
      <ringLength>1</ringLength>
      <ringDepth>0.3</ringDepth>
      <ringAddition>1.2</ringAddition>
      <sendShipTime>0.3</sendShipTime>
      <sendShipNum>5</sendShipNum>
      <starDes>Star Me</starDes>
    </star>
    <star>
      <starId>2</starId>
      <masterId>2</masterId>
      <starParentId>-1</starParentId>
      <rotateSpeed>0</rotateSpeed>
      <position>
        <x>8</x>
        <y>2</y>
        <z>20</z>
      </position>
      <starType>TroopStar</starType>
      <starLevel>1</starLevel>
      <maxTroop>30</maxTroop>
      <startTroopNum>30</startTroopNum>
      <bornTime>1.5</bornTime>
      <bornNum>1</bornNum>
      <detectScope>2</detectScope>
      <shipFlySpeed>2</shipFlySpeed>
      <shipShowType>Cloud</shipShowType>
      <thinkTime>3</thinkTime>
      <ringLength>1</ringLength>
      <ringDepth>0.3</ringDepth>
      <ringAddition>1.2</ringAddition>
      <sendShipTime>0.2</sendShipTime>
      <sendShipNum>1</sendShipNum>
      <starDes>Star 2</starDes>
    </star>
    <star>
      <starId>3</starId>
      <masterId>0</masterId>
      <starParentId>-1</starParentId>
      <rotateSpeed>0</rotateSpeed>
      <position>
        <x>-7</x>
        <y>1</y>
        <z>10</z>
      </position>
      <starType>TroopStar</starType>
      <starLevel>0</starLevel>
      <maxTroop>30</maxTroop>
      <startTroopNum>10</startTroopNum>
      <bornTime>1</bornTime>
      <bornNum>1</bornNum>
      <detectScope>2</detectScope>
      <shipFlySpeed>2</shipFlySpeed>
      <shipShowType>Cloud</shipShowType>
      <thinkTime>3</thinkTime>
      <ringLength>1</ringLength>
      <ringDepth>0.3</ringDepth>
      <ringAddition>1.2</ringAddition>
      <sendShipTime>0.3</sendShipTime>
      <sendShipNum>5</sendShipNum>
      <starDes>Star None</starDes>
    </star>
    <star>
      <starId>4</starId>
      <masterId>0</masterId>
      <starParentId>-1</starParentId>
      <rotateSpeed>0</rotateSpeed>
      <position>
        <x>7</x>
        <y>-1</y>
        <z>10</z>
      </position>
      <starType>TroopStar</starType>
      <starLevel>0</starLevel>
      <maxTroop>30</maxTroop>
      <startTroopNum>10</startTroopNum>
      <bornTime>1</bornTime>
      <bornNum>1</bornNum>
      <detectScope>2</detectScope>
      <shipFlySpeed>2</shipFlySpeed>
      <shipShowType>Cloud</shipShowType>
      <thinkTime>3</thinkTime>
      <ringLength>1</ringLength>
      <ringDepth>0.3</ringDepth>
      <ringAddition>1.2</ringAddition>
      <sendShipTime>0.3</sendShipTime>
      <sendShipNum>5</sendShipNum>
      <starDes>Star None</starDes>
    </star>
    <star>
      <starId>5</starId>
      <masterId>0</masterId>
      <starParentId>-1</starParentId>
      <rotateSpeed>0</rotateSpeed>
      <position>
        <x>-5</x>
        <y>-3</y>
        <z>10</z>
      </position>
      <starType>TroopStar</starType>
      <starLevel>0</starLevel>
      <maxTroop>30</maxTroop>
      <startTroopNum>15</startTroopNum>
      <bornTime>1</bornTime>
      <bornNum>1</bornNum>
      <detectScope>2</detectScope>
      <shipFlySpeed>2</shipFlySpeed>
      <shipShowType>Cloud</shipShowType>
      <thinkTime>3</thinkTime>
      <ringLength>1</ringLength>
      <ringDepth>0.3</ringDepth>
      <ringAddition>1.2</ringAddition>
      <sendShipTime>0.3</sendShipTime>
      <sendShipNum>5</sendShipNum>
      <starDes>Star None</starDes>
    </star>
    <star>
      <starId>6</starId>
      <masterId>0</masterId>
      <starParentId>-1</starParentId>
      <rotateSpeed>0</rotateSpeed>
      <position>
        <x>5</x>
        <y>3</y>
        <z>10</z>
      </position>
      <starType>TroopStar</starType>
      <starLevel>0</starLevel>
      <maxTroop>30</maxTroop>
      <startTroopNum>15</startTroopNum>
      <bornTime>1</bornTime>
      <bornNum>1</bornNum>
      <detectScope>2</detectScope>
      <shipFlySpeed>2</shipFlySpeed>
      <shipShowType>Cloud</shipShowType>
      <thinkTime>3</thinkTime>
      <ringLength>1</ringLength>
      <ringDepth>0.3</ringDepth>
      <ringAddition>1.2</ringAddition>
      <sendShipTime>0.3</sendShipTime>
      <sendShipNum>5</sendShipNum>
      <starDes>Star None</starDes>
    </star>
  </starList>
</level>
